### ISSUE TITLE
Create a stylesheet and link it in

### ISSUE THREAD

**Issue by codeTrackLift** [codepharm/git#4]
Notes:
- create `styles` folder
- name the stylesheet `styles.css` and place in the `styles folder`
- add a background
- add a header with some intro text

**Comment by developer-irfan** [comment]
@codeTrackLift assign me this task i will crate style file add bg with some intro.

**Comment by codeTrackLift** [comment]
Related PR #6

**Comment by nettle790** [comment]
Please elaborate.trying to make sense of this reply.

**Comment by codeTrackLift** [comment]
> Please elaborate.trying to make sense of this reply.
> […](#)
> Sent from my iPhone
> On 10-Sep-2022, at 10:39 PM, Pete Chu ***@***.***> wrote: ﻿ Related PR #6 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were assigned.

The reply above is intended to link related PR that is related to this issue. This makes it easier to trace the work in response to the issue, and also updating the project board.

https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

**Comment by nettle790** [comment]
I was just perusing your overview page and there is a significant typo error in the about me section ,list line-4… it is internship not intership.

**Comment by codeTrackLift** [comment]
Thanks @nettle790, appreciate it! 🙏

**Comment by nettle790** [comment]
👍.Linked the PR with issue#4.please check if it's right.

**Comment by nettle790** [comment]
I can create a stylesheet yes but where do you want it to link To???

**Comment by codeTrackLift** [comment]
I would add the stylesheet link in the `<head>` of the index.html.

I think that's already done in PR #6

**Comment by nettle790** [comment]
yes that is obvious.then y is there a open good first issue tagged  to it?

**Comment by codeTrackLift** [comment]
Because I tagged this for you to work on.

**Comment by nettle790** [comment]
so I continue working on the same branch?????

**Comment by nettle790** [comment]
before I continue thanks for having the patience to mentor me.

**Comment by codeTrackLift** [comment]
You're welcome.

Yes - the intent is the start with the Issue.  The PR and your branch is in response to this Issue.

**Comment by nettle790** [comment]
can I add items to the project board or is it that only you can add items?? Please send me link of projects in docs.

**Comment by codeTrackLift** [comment]
I don't think you can directly add content to the GH Projects Kanban board.  They are linked via issues and PRs, see documentation below.
[GH Projects](https://docs.github.com/en/issues/planning-and-tracking-with-projects/learning-about-projects/about-projects)

By the way, there are still 3 `pending` comments on [PR#6](https://github.com/codepharm/git/pull/6).  Suggestion is to resolve these before creating any new issues.  Let me know with questions, thanks.

**Comment by nettle790** [comment]
what should be done in PR#6?.sorry I am kind of lost as to how to proceed.

**Comment by nettle790** [comment]
Meanwhile I have been  adding content to readme trying to figure out how to proceed.???

**Comment by codeTrackLift** [comment]
Please see each comment in [PR#6](https://github.com/codepharm/git/pull/6) for details.  Three of them have the orange `pending` tag.

See GH docs below for more info on commenting in general.
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/commenting-on-a-pull-request

**Comment by nettle790** [comment]
I see no pending tags anywhere in #6.

**Comment by codeTrackLift** [comment]
<img width="711" alt="Screen Shot 2022-09-22 at 1 26 44 PM" src="https://user-images.githubusercontent.com/96446064/191812639-135f053e-522e-458f-b8f1-14dbe9bfa83d.png">

**Comment by nettle790** [comment]
I don't see any of these comments nor the pending tag.

**Comment by nettle790** [comment]
how did this happen??wasted precious time.

**Comment by nettle790** [comment]
type=text/css is harmless, as a precaution.if you think its still not needed I will remove it.please review the changes.
